import React from 'react'
import Post from './Post'

export const Posts= 
[
    {
        id:"121",
        username:"Teacher jara",
        classpost:"grade 6",
        timeafterpost:"mar 20",
        userimg:"assets/profile/1.jpg",
        img:"assets/1.jpg",
        caption:"i think we progressed 1% out of 100",
        nooflike:"15",
        noofcomments:"6",
    },
    {
        id:"122",
        username:"Teacher Giri",
        classpost:"grade 8",
        timeafterpost:"mar 25",
        userimg:"assets/profile/2.jpg",
        img:"assets/2.jpg",
        caption:"grade 8s are retarded",
        nooflike:"176",
        noofcomments:"65",
    },
    {
        id:"123",
        username:"Teacher dano",
        classpost:"grade 2",
        timeafterpost:"Mar 30",
        userimg:"assets/profile/3.jpg",
        img:"assets/3.jpg",
        caption:"grade 2s are the best",
        nooflike:"5",
        noofcomments:"2",
    },
    {
        id:"123",
        username:"Teacher ned",
        classpost:"grade 8",
        timeafterpost:"Apr 20",
        userimg:"assets/profile/4.jpg",
        img:"assets/4.jpg",
        caption:"grade 2 teachers are retarded",
        nooflike:"115",
        noofcomments:"46",
    },
    {
        id:"123",
        username:"Teacher girum hawasa",
        classpost:"grade 1",
        timeafterpost:"mar 20",
        userimg:"assets/profile/5.jpg",
        img:"assets/5.jpg",
        caption:"I love grade 2",
        nooflike:"154",
        noofcomments:"16",
    },
    {
        id:"123",
        username:"Teacher junior",
        classpost:"grade 8",
        timeafterpost:"mar 20",
        userimg:"assets/profile/6.jpg",
        img:"assets/6.jpg",
        caption:"good progress",
        nooflike:"515",
        noofcomments:"65",
    },
];
